#define VIEW_PORT_DEC_SIZE 0.75
#define TOOL_BAR_HEIGHT 56
#define BUTTON_SPACING 2
#define BUTTON_SIZE (TOOL_BAR_HEIGHT - 24)
#define TOOL_BAR_PADDING 12
#define INSPECTOR_WIDTH 320
#define DEFAULT_SCREEN_WIDTH 1280
#define DEFAULT_SCREEN_HEIGHT 720
#define NEW_ICON "#8#"
#define OPEN_ICON "#1#"
#define SAVE_ICON "#2#"
#define EXPORT_ICON "#7#"
